name: Bryan
favicon: null
layout_spectrum: 0.7909575942903757
typography_spectrum: 0.41041454765945673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.38041732157580554
  lightness: 0.8733847718685865
  saturation: 0.11810958315618336
  rhythmicContrast: 0.852248068433255
purpose: []
